Numpy is one of the essential libraries for Machine Learning. It helps to econom time and resource in data Pre-processing and later on implementing machine learning algorithms.

This notebook serve as a quick refresher to Numpy.

Numpy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

[Source](https://medium.com/@sid_darthvader/an-essential-guide-to-numpy-for-machine-learning-in-python-5615e1758301)

In [1]:
from jyquickhelper import add_notebook_menu
add_notebook_menu(last_level=3)

## 1. Creating a vector

In [1]:
# load library
import numpy as np

# create a vector as a row
vector_row = np.array([1,2,3])

print('Vector_row:', vector_row, 'Shape:', vector_row.shape)

# create vector as a column
vector_column = np.array([[1], [2], [3]])
print('Vector_column:\n', vector_column, '\nShape:', vector_column.shape)

Vector_row: [1 2 3] Shape: (3,)
Vector_column:
 [[1]
 [2]
 [3]] 
Shape: (3, 1)


## 2. Creating a matrix

In [2]:
import numpy as np

# create matrix
matrix = np.array([[1,2,3], [4,5,6]])
print('Matrix:\n', matrix, '\nShape:', matrix.shape)

matrix2 = np.matrix([1,2,3])
print('Another matrix:', matrix2, '\nShape:', matrix2.shape)     
      

Matrix:
 [[1 2 3]
 [4 5 6]] 
Shape: (2, 3)
Another matrix: [[1 2 3]] 
Shape: (1, 3)


## 2'. Creating a Sparse Matrix with Scipy

Given data with very few non zero values you want to efficiently represent it.

Sparse Matrices store only non zero elements and assume all other values will be zero, leading to significant computational savings.

In [3]:
#Create a Matrix with numpy
import numpy as np
matrix = np.array([[0,0],[0,1],[3,0]])
print('Full matrix:\n', matrix)

#Create Compressed Sparse Row(CSR) matrix
import scipy.sparse as sparse
matrix_sparse = sparse.csr_matrix(matrix)
print('\nSparse matrix:\n', matrix_sparse)

Full matrix:
 [[0 0]
 [0 1]
 [3 0]]

Sparse matrix:
   (1, 1)	1
  (2, 0)	3


## 3. Selecting elements

In [4]:
#Load Library
import numpy as np

#Create a vector as a Row
vector_row = np.array([ 1,2,3,4,5,6 ])
print('Vector:', vector_row)

#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Matrix:\n', matrix, '\n')

#Select 3rd element of Vector
print('3rd element of Vector:', vector_row[2])

#Select 2nd row 2nd column
print('2nd element of 2nd row:', matrix[1,1])

#Select all elements of a vector
print('All elements of Vector:', vector_row[:])

#Select everything up to and including the 3rd element
print('First 3 elements of Vector:', vector_row[:3])

#Select the everything after the 3rd element
print('All beside first 3 elements of Vector:', vector_row[3:])

#Select the last element
print('Last element of Vector:', vector_row[-1], '\n')

#Select the first 2 rows and all the columns of the matrix
print('First 2 rows of Matrix:\n', matrix[:2,:])

#Select all rows and the 2nd column of the matrix
print('2nd column of Matrix:\n', matrix[:,1:2])

Vector: [1 2 3 4 5 6]
Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

3rd element of Vector: 3
2nd element of 2nd row: 5
All elements of Vector: [1 2 3 4 5 6]
First 3 elements of Vector: [1 2 3]
All beside first 3 elements of Vector: [4 5 6]
Last element of Vector: 6 

First 2 rows of Matrix:
 [[1 2 3]
 [4 5 6]]
2nd column of Matrix:
 [[2]
 [5]
 [8]]


## 4. Describing a Matrix

In [5]:
import numpy as np

#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Matrix:\n', matrix, '\n')

#View the Number of Rows and Columns
print('Number of Rows and Columns:', matrix.shape)

#View the number of elements (rows*columns)
print('Number of elements:', matrix.size)

#View the number of Dimensions(2 in this case)
print('Number of dimensions', matrix.ndim)

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

Number of Rows and Columns: (3, 3)
Number of elements: 9
Number of dimensions 2


## 5. Applying operations to elements

In [6]:
#Load Library
import numpy as np

#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Matrix:\n', matrix)

#Create a function that adds 100 to something
add_100 = lambda i: i+100

#Convert it into a vectorized function
vectorized_add_100 = np.vectorize(add_100)

#Apply function to all elements in matrix
print('Add 100 to all element:\n', vectorized_add_100(matrix))

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Add 100 to all element:
 [[101 102 103]
 [104 105 106]
 [107 108 109]]


 ## 6. Finding the max and min values

In [7]:
#Load Library
import numpy as np

#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Matrix:\n', matrix)

#Return the max element
print('Max:', np.max(matrix), matrix.max())

#Return the min element
print('Min:', np.min(matrix), matrix.min())

#To find the max element in each column
print('Max in each column:', np.max(matrix,axis=0), matrix.max(axis=0))

#To find the max element in each row
print('Min in each row:', np.min(matrix,axis=1), matrix.min(axis=1))

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Max: 9 9
Min: 1 1
Max in each column: [7 8 9] [7 8 9]
Min in each row: [1 4 7] [1 4 7]


## 7. Calculating Average, Variance and Standard deviation

In [8]:
#Load Library
import numpy as np

#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Matrix:\n', matrix)

#Mean
print('Mean:', np.mean(matrix), matrix.mean())

#Standard Dev.
print('Atandard deviation:', np.std(matrix), matrix.std())

#Variance
print('Variance:', np.var(matrix), matrix.var())

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Mean: 5.0 5.0
Atandard deviation: 2.581988897471611 2.581988897471611
Variance: 6.666666666666667 6.666666666666667


## 8. Reshaping Arrays

In [9]:
#Load Library
import numpy as np

#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6]])
print('Matrix:\n', matrix)

#Reshape
print('Each element in row:\n', matrix.reshape(6,1))

#Here -1 says as many columns as needed and 1 row
print('All element in a row (reshape with -1):', matrix.reshape(1,-1))

#If we provide only 1 value Reshape would return a 1-d array of that length
print('All element in a row (reshape with size):', matrix.reshape(6))

#We can also use the Flatten method to convert a matrix to 1-d array
print('All element in a row (reshape with flatten):', matrix.flatten())

Matrix:
 [[1 2 3]
 [4 5 6]]
Each element in row:
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
All element in a row (reshape with -1): [[1 2 3 4 5 6]]
All element in a row (reshape with size): [1 2 3 4 5 6]
All element in a row (reshape with flatten): [1 2 3 4 5 6]


## 9. Transposing a Matrix

In [10]:
#Load Library
import numpy as np

#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Matrix:\n', matrix)

#Transpose the matrix
print('Transposed matrix:\n', matrix.T)

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transposed matrix:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


## 10. Finding the Determinant and Rank of a Matrix

In [11]:
#Load Library
import numpy as np

#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Matrix:\n', matrix)

#Calculate the Determinant
print('Determinant: ', np.linalg.det(matrix))

#Calculate the Rank
print('Rank:', np.linalg.matrix_rank(matrix))

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Determinant:  -9.51619735392994e-16
Rank: 2


## 11. Getting the Diagonal of a Matrix

In [12]:
#Load Library
import numpy as np

#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Matrix:\n', matrix)

#Print the Principal diagonal
print('Principal diagonal:', matrix.diagonal())

#Print the diagonal one above the Principal diagonal
print('One above:', matrix.diagonal(offset=1))

#Print the diagonal one below Principal diagonal
print('One below:', matrix.diagonal(offset=-1))

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Principal diagonal: [1 5 9]
One above: [2 6]
One below: [4 8]


## 12. Calculating the trace of a Matrix
Trace of a Matrix is the sum of elements on the Principal Diagonal of the Matrix.

In [13]:
#Load Library
import numpy as np

#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Matrix:\n', matrix)

#Print the Trace
print('Trace:', matrix.trace())

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Trace: 15


## 13. Finding Eigenvalues and Eigenvectors

Eigenvectors are widely used in Machine Learning libraries. Intutively given a linear transformation represented by a matrix $\mathbf{A}$, eigenvectors are vectors that when that transformation is applied, change only in scale(not direction). More formally:

$$\mathbf{A}\cdot\boldsymbol{v} = \boldsymbol{K}\boldsymbol{v}$$

where:
- $\mathbf{A}$ squared matrix
- $\boldsymbol{K}$ contains eigenvalues
- $\boldsymbol{v}$ contains eigenvectors

In [14]:
#Load Library
import numpy as np

#Create a Matrix
matrix = np.arange(1,17).reshape(4,4)
print('Matrix:\n', matrix)

# Calculate the Eigenvalues and Eigenvectors of that Matrix
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print('Eigenvalues:', eigenvalues)
print('Eigenvectors:', eigenvectors)

Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Eigenvalues: [ 3.62093727e+01 -2.20937271e+00 -2.91421324e-15 -5.70557534e-16]
Eigenvectors: [[-0.15115432  0.72704996 -0.36400894  0.00610215]
 [-0.34923733  0.28320876  0.79039305  0.40008675]
 [-0.54732033 -0.16063243 -0.4887593  -0.81847996]
 [-0.74540333 -0.60447363  0.06237518  0.41229105]]


## 14. Calculating Dot Products

In [15]:
#Load Library
import numpy as np

#Create vector-1
vector_1 = np.array([1, 2, 3])
print('1st vector:', vector_1)
#Create vector-2
vector_2 = np.array([4, 5, 6])
print('2nd vector:', vector_2)

#Calculate Dot Product
print('Dot Product:', np.dot(vector_1,vector_2))

#Alternatively you can use @ to calculate dot products
print('Dot Product:', vector_1 @ vector_2)

1st vector: [1 2 3]
2nd vector: [4 5 6]
Dot Product: 32
Dot Product: 32


## 15. Adding, Subtracting and Multiplying Matrices

In [16]:
#Load Library
import numpy as np

#Create Matrix-1
matrix_1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('1st matrix:\n', matrix_1)

#Create Matrix-2
matrix_2 = np.array([[7,8,9],[4,5,6],[1,2,3]])
print('2nd matrix:\n', matrix_2)

#Add the 2 Matrices
print('Sum:\n', np.add(matrix_1,matrix_2))

#Subtraction
print('Subtract:\n', np.subtract(matrix_1,matrix_2))

#Multiplication(Element wise, not Dot Product)
print('Element-wise product:\n', matrix_1*matrix_2)

1st matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
2nd matrix:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
Sum:
 [[ 8 10 12]
 [ 8 10 12]
 [ 8 10 12]]
Subtract:
 [[-6 -6 -6]
 [ 0  0  0]
 [ 6  6  6]]
Element-wise product:
 [[ 7 16 27]
 [16 25 36]
 [ 7 16 27]]


## 16. Inverting a Matrix

In [17]:
#Load Library
import numpy as np

#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[8,7,9]])
print('Matrix:', matrix)

#Calculate its inverse
print('Inverse matrix:\n', np.linalg.inv(matrix))

Matrix: [[1 2 3]
 [4 5 6]
 [8 7 9]]
Inverse matrix:
 [[-0.33333333 -0.33333333  0.33333333]
 [-1.33333333  1.66666667 -0.66666667]
 [ 1.33333333 -1.          0.33333333]]


## 17. Generating Random values

In [18]:
#Load Library
import numpy as np

#Set seed
np.random.seed(1)

#Generate 3 random integers b/w 1 and 10
print('Random number b/w 1 and 10:', np.random.randint(0,11,3))

#Draw 3 numbers from a normal distribution with mean 1.0 and std 2.0
print('Normal distribution:\n', np.random.normal(1.0, 2.0, 10))
print('Uniform distribution:\n', np.random.uniform(0, 1, 10))

# See more generation method at np.random

Random number b/w 1 and 10: [5 8 9]
Normal distribution:
 [-0.60434568  0.10224438 -1.21187015 -2.3090309  -3.72693721  3.2706907
 -1.03402827  2.27472363 -0.71981321  4.54521526]
Uniform distribution:
 [0.55868983 0.14038694 0.19810149 0.80074457 0.96826158 0.31342418
 0.69232262 0.87638915 0.89460666 0.08504421]
